ThAmCo.Events/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Data;
using ThAmCo.Events.Models;

namespace ThAmCo.Events.Controllers
{
    /// <summary>
    /// The controller for the customers data type
    /// </summary>
    public class CustomersController : Controller
    {
        /// <summary>
        /// The dbContext to be used
        /// </summary>
        private readonly EventsDbContext _context;

        /// <summary>
        /// Initialises a new controller
        /// </summary>
        /// <param name="context">The context to be used by the controller</param>
        public CustomersController(EventsDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Gets a view containing the list of all customers
        /// </summary>
        /// <returns>The index view of all customers</returns>
        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customers.ToListAsync());
        }

        /// <summary>
        /// Gets the details of one specific Customer
        /// Joins it to the GuestBookings list for that Customer
        /// </summary>
        /// <param name="id">The id of the customer whose details are needed</param>
        /// <returns>A view containing the details of the Customer</returns>
        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                                         .Select(c => new CustomerDetails
                                         {
                                            Id = c.Id,
                                            FirstName = c.FirstName,
                                            LastName = c.Surname,
                                            Email = c.Email,
                                            Events = _context.Guests
                                                             .Where(g => g.CustomerId == c.Id)
                                                             .Select(e => new _Event
                                                             {
                                                                Id = e.Event.Id,
                                                                Date = e.Event.Date,
                                                                Title = e.Event.Title,
                                                                TypeId = e.Event.TypeId
                                                             })
                                         })
                                         .FirstOrDefaultAsync(m => m.Id == id);


            if (customer == null)
            {
                return NotFound();
            }

            ViewData["CustomerName"] = customer.FirstName + " " + customer.LastName;
            return View(customer);
        }

        /// <summary>
        /// Gets the create view for a customer
        /// </summary>
        /// <returns>The Create view for the customer</returns>
        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Adds a new Customer to the dbContext
        /// </summary>
        /// <param name="customer">The Customer object to be added</param>
        /// <returns>The index view if successful, otherwise the Create view</returns>
        // POST: Customers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Surname,FirstName,Email")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        /// <summary>
        /// Returns the edit view for a customer data object
        /// Data fields are initialised to match data
        /// </summary>
        /// <param name="id">The id of the customer to edit</param>
        /// <returns>The edit view, fields populated</returns>
        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        /// <summary>
        /// Edits a Customer in the dbContext
        /// </summary>
        /// /// <param name="id">The id of the Customer object to be edited</param>
        /// <param name="customer">The Customer object to be edited</param>
        /// <returns>The index view if successful, otherwise the Edit view</returns>
        // POST: Customers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Surname,FirstName,Email")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        /// <summary>
        /// Gets a delete view for a customer
        /// </summary>
        /// <param name="id">The id of the customer to delete</param>
        /// <returns>The details view of the customer to delete</returns>
        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        /// <summary>
        /// Deletes a customer from the db Context
        /// </summary>
        /// <param name="id">The id of the customer to delete</param>
        /// <returns>The index view</returns>
        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Checks if a customer exists
        /// </summary>
        /// <param name="id">The id of the customer to check</param>
        /// <returns>True if the customer exists, false if not</returns>
        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.Id == id);
        }
    }
}

ThAmCo.Events/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using ThAmCo.Events.Data;
using ThAmCo.Events.Models;
using ThAmCo.Venues.Models;

namespace ThAmCo.Events.Controllers
{
    /// <summary>
    /// The controller for the events data type
    /// </summary>
    public class EventsController : Controller
    {
        /// <summary>
        /// The dbContext to be used
        /// </summary>
        private readonly EventsDbContext _context;

        /// <summary>
        /// Initialises a new controller
        /// </summary>
        /// <param name="context">The context to be used by the controller</param>
        public EventsController(EventsDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Gets a view containing the list of all events
        /// </summary>
        /// <returns>The index view of all events</returns>
        // GET: Events
        public async Task<IActionResult> Index()
        {
            var eventsDbContext = _context.Events
                                          .Where(e => e.IsActive);

            var events = await eventsDbContext.ToListAsync();

            List<EventList> eventlists = new List<EventList>();

            foreach (Event e in events)
            {
                EventList el = new EventList();

                el.Date = e.Date;
                el.Duration = e.Duration;
                el.Id = e.Id;
                el.IsActive = e.IsActive;
                el.Title = e.Title;
                el.GuestCount = _context.Guests
                                 .Where(g => g.EventId == e.Id)
                                 .Count();

                el.Venue = (e.Venue == null) ? "No Venue Booked" : e.Venue ;
                eventlists.Add(el);
            }

            return View(eventlists);
        }

        /// <summary>
        /// Gets the details of one specific Event
        /// Joins it to the GuestBookings list and Staff List for that Event
        /// </summary>
        /// <param name="id">The id of the event whose details are needed</param>
        /// <returns>A view containing the details of the event</returns>
        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                                       .Select(e => new EventDetails
                                       {
                                           Id = e.Id,
                                           IsActive = e.IsActive,
                                           Title = e.Title,
                                           Date = e.Date,
                                           Duration = e.Duration,
                                           TypeId = e.TypeId,
                                           Venue = e.Venue,
                                           GuestCount = _context.Guests.Where(v => v.EventId == e.Id).Count(),
                                           Menu = e.Menu,
                                           FoodCost = e.FoodCost.ToString("C2"),
                                           VenueCost = e.VenueCost.ToString("C2"),
                                           
                                           Guests = _context.Guests
                                                            .Where(g => g.EventId == e.Id)
                                                            .Select(g => new EventGuest
                                                            {
                                                                Id = g.Customer.Id,
                                                                Name = g.Customer.FirstName + " " + g.Customer.Surname,
                                                                Email = g.Customer.Email,
                                                                Attended = g.Attended
                                                            }),
                                           Staff = _context.Workers
                                                           .Where(w => w.EventId == e.Id)
                                                           .Select(w => new EventStaff
                                                           {
                                                               Id = w.Staff.Id,
                                                               StaffCode = w.Staff.StaffCode,
                                                               Name = w.Staff.FirstName + " " + w.Staff.Surname
                                                           })
                                       })
                                       .FirstOrDefaultAsync(m => m.Id == id);

            var guestList = _context.Guests.Where(v => v.EventId == @event.Id);
            var staffList = _context.Workers.Where(v => v.EventId == @event.Id);

            int guestCount = guestList.Count();
            int staffCount = staffList.Count();

            @event.CorrectStaff = (staffCount > 0 && staffCount >= (guestCount / 10));
            @event.FirstAider = (staffList.Where(s => s.Staff.FirstAider).Count() > 0);

            decimal FoodCost = Convert.ToDecimal(@event.FoodCost.Substring(1));
            decimal VenueCost = Convert.ToDecimal(@event.VenueCost.Substring(1));

            @event.TotalFoodCost = (FoodCost * @event.GuestCount).ToString("C2");
            @event.TotalCost = ((FoodCost * @event.GuestCount) + VenueCost).ToString("C2");

            if (@event == null)
            {
                return NotFound();
            }

            ViewData["EventTitle"] = @event.Title;

            return View(@event);
        }

        /// <summary>
        /// Gets the create view for an event
        /// </summary>
        /// <returns>The Create view for the event</returns>
        // GET: Events/Create
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Adds a new Event to the dbContext
        /// </summary>
        /// <param name="@event">The Customer object to be added</param>
        /// <returns>The index view if successful, otherwise the Create view</returns>
        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Date,Duration,TypeId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                @event.IsActive = true;
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        /// <summary>
        /// Returns the edit view for an event data object
        /// Data fields are initialised to match data
        /// </summary>
        /// <param name="id">The id of the event to edit</param>
        /// <returns>The edit view, fields populated</returns>
        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Event @event = await _context.Events.FindAsync(id);
            if (@event == null || !@event.IsActive)
            {
                return NotFound();
            }
            
            EventEdit eventEdit = new EventEdit
            {
                Id = @event.Id,
                Title = @event.Title,
                Date = @event.Date,
                Duration = @event.Duration,
                TypeId = @event.TypeId
            };
            
            return View(@eventEdit);
        }

        /// <summary>
        /// Edits an event in the dbContext
        /// </summary>
        /// <param name="eventEdit">The Event object to be edited</param>
        /// <returns>The index view if successful, otherwise the Edit view</returns>
        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Duration")] EventEdit eventEdit)
        {
            if (id != @eventEdit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Event @event = _context.Events.Find(id);

                @event.Title = eventEdit.Title;
                @event.Duration = eventEdit.Duration;

                try
                {
                    @event.IsActive = true;
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));

ThAmCo.Events/Views/Events/AvailableMenus.cshtml
@model IEnumerable<ThAmCo.Events.Models.FoodMenu>

@{
    ViewData["Title"] = "AvailableMenus";
}

<h2>AvailableMenus</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Starter)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Main)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dessert)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Starter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Main)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dessert)
            </td>
            <td>
                £@Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.ActionLink("Book", "BookMenu", "Events", new { eventId = ViewData["EventId"], menuId = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

ThAmCo.Events/Views/Events/AvailableVenues.cshtml
@model IEnumerable<ThAmCo.Events.Models.AvailableVenuesDto>

@{
    ViewData["Title"] = "Available Venues";
}

<h2>Available Venues for @ViewData["EventTitle"]</h2>

@if (((SelectList)ViewData["VenueList"]).Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Code)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Capacity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CostPerHour)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Capacity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CostPerHour)
                    </td>
                </tr>
            }
        </tbody>

    </table>

    @using (Html.BeginForm("ReserveVenue", "Events", FormMethod.Get))
    {
        @Html.DropDownList("venueCode", (SelectList)ViewData["VenueList"])
        @Html.DropDownList("staffId", (SelectList)ViewData["StaffList"]);
        <input type="hidden" id="eventId" value="@ViewData["EventId"]" name="eventId" />

        <input type="Submit" name="btnSubmit" />
    }
}
else
{
    <p>No Venues Available</p>
}

ThAmCo.Events/Views/Events/BookMenu.cshtml
@model ThAmCo.Events.Models.FoodMenu

@{
    ViewData["Title"] = "BookMenu";
}

<h2>BookMenu</h2>

<div>
    <h4>FoodMenuViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Starter)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Starter)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Main)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Main)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Dessert)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Dessert)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Details" asp-route-id ="@ViewData["EventId"]">Back to Event</a>
</div>

ThAmCo.Events/Views/Events/Delete.cshtml
@model ThAmCo.Events.Data.Event

@{
    ViewData["Title"] = "Delete";
}

<h2>Cancel</h2>

<h3>Are you sure you want to cancel this event?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TypeId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TypeId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ThAmCo.Events/Views/Events/Details.cshtml
@model ThAmCo.Events.Models.EventDetails

@{
    ViewData["Title"] = "Details";
}

<h2>@ViewData["EventTitle"] Details</h2>

<div class="row">
    <div class="col-md-3">
        <h4>Event</h4> <br />
        <hr />
        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Duration)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Duration)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.GuestCount)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.GuestCount)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Menu)
            </dt>
            <dd>
                @if (Model.Menu != null)
                {
                    @Html.DisplayFor(model => model.Menu) <br />
                    @Html.ActionLink("Change Food", "AvailableMenus", "Events", new { eventid = Model.Id }) <br />
                    @Html.ActionLink("Cancel Food", "CancelMenu", "Events", new { eventid = Model.Id })
                }
                else
                {
                    @Html.ActionLink("Book Food", "AvailableMenus", "Events", new { eventid = Model.Id })
                }
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.FoodCost)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.FoodCost)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TotalFoodCost)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TotalFoodCost)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Venue)
            </dt>
            <dd>
                @if (Model.Venue != null)
                {
                    @Html.DisplayFor(model => model.Venue)
                }
                else
                {
                    @Html.ActionLink("Book Venue", "AvailableVenues", "Events", new { eventid = Model.Id })
                }
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.VenueCost)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.VenueCost)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TotalCost)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TotalCost)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CorrectStaff)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CorrectStaff)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.FirstAider)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.FirstAider)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TypeId)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TypeId)
            </dd>
        </dl>
    </div>
    <div class="col-md-5">
        <h4>Guests</h4>
        <a asp-controller="GuestBookings" asp-action="Create" asp-route-eventid="@Model.Id">Add Guest</a> | <a asp-controller="GuestBookings" asp-action="Delete" asp-route-eventid="@Model.Id">Remove Guest</a>
        <hr />
        @if (Model.Guests.Any())
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Email
                        </th>
                        <th>
                            Attended?
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Guests)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Attended)
                            </td>
                            <td>
                                @Html.ActionLink("Details", "Details", "Customers", new { id = item.Id }) |
                                @Html.ActionLink("Attendance", "Edit", "GuestBookings", new { eventid = Model.Id, customerid = item.Id })

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No Guests booked</p>
        }
    </div>
    <div class="col-md-4">
        <h4>Staff</h4>
        <a asp-controller="Staffings" asp-action="Create" asp-route-eventid="@Model.Id">Add Staff</a> | <a asp-controller="Staffings" asp-action="Delete" asp-route-eventid="@Model.Id">Remove Staff</a>
        <hr />
        @if (Model.Staff.Any())
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            Staff Code
                        </th>
                        <th>
                            Name
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Staff)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.StaffCode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.ActionLink("Details", "Details", new { id = item.Id })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No Staff scheduled</p>
        }
    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>