ThAmCo.Events/Models/ViewModels/Venues.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ThAmCo.Events.Models
{
    /// <summary>
    /// The model used for the venues index view
    /// </summary>
    public class Venues
    {
        /// <summary>
        /// The code of the venue
        /// </summary>
        [Key, MinLength(5), MaxLength(5)]
        public string Code { get; set; }

        /// <summary>
        /// The name of the venue
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// The description of the venue and all its features
        /// </summary>
        [Required]
        public string Description { get; set; }

        /// <summary>
        /// How many people the venue can hold
        /// </summary>
        [Range(1, Int32.MaxValue)]
        public int Capacity { get; set; }
    }
}

ThAmCo.Events/Controllers/VenuesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Data;
using ThAmCo.Events.Models;
using ThAmCo.Venues.Data;

namespace ThAmCo.Events.Controllers
{
    /// <summary>
    /// The controller for the FoodMenus data type
    /// </summary>
    public class VenuesController : Controller
    {
        /// <summary>
        /// The dbContext to be used
        /// </summary>
        private readonly EventsDbContext _context;

        /// <summary>
        /// Initialises the controller and the dbContext
        /// </summary>
        public VenuesController(EventsDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Gets a view containing the list of all menus
        /// Pushes a get statement to the Menus api
        /// </summary>
        /// <returns>The index view of all menus</returns>
        // GET: VenuesViewModels
        public async Task<IActionResult> Index(string eventType, DateTime beginDate, DateTime endDate)
        {
            eventType = eventType ?? "WED";

            Debug.WriteLine(endDate);

            DateTime empty = new DateTime();
            beginDate = (beginDate == empty) ? DateTime.MinValue : beginDate;
            endDate = (endDate == empty) ? DateTime.MaxValue : endDate;

            var availableVenues = new List<AvailableVenuesDto>().AsEnumerable();

            HttpClient client = getClient("23652");

            Debug.WriteLine(eventType);
            Debug.WriteLine(beginDate);
            Debug.WriteLine(endDate);

            HttpResponseMessage response = await client.GetAsync("api/Availability?eventType=" + eventType
                + "&beginDate=" + beginDate.ToString("yyyy/MM/dd")
                + "&endDate=" + endDate.ToString("yyyy/MM/dd"));

            if (response.IsSuccessStatusCode)
            {
                availableVenues = await response.Content.ReadAsAsync<IEnumerable<AvailableVenuesDto>>();

                if (availableVenues.Count() == 0)
                {
                    Debug.WriteLine("No available menus");
                }
            }
            else
            {
                Debug.WriteLine("Recieved a bad response from service");
            }

            var eventTypesResponse = await client.GetAsync("api/EventTypes");
            var eventTypes = await eventTypesResponse.Content.ReadAsAsync<IEnumerable<EventType>>();

            ViewData["EventTypes"] = new SelectList(eventTypes, "Id", "Title");
            ViewData["EventType"] = eventType;

            return View(availableVenues);
        }

        /// <summary>
        /// Creates a new event for the selected Availalibity
        /// </summary>
        /// <param name="venueCode">the code of the venue to be selected</param>
        /// <param name="eventType">the event type</param>
        /// <param name="date">The date of the event</param>
        /// <returns>The create view initialised with values</returns>
        public IActionResult CreateEvent(string venueCode, string eventType, DateTime date)
        {
            if (venueCode == null || eventType == null)
            {
                return NotFound();
            }

            Debug.WriteLine(date);

            var @event = new VenueEvent
            {
                Venue = venueCode,
                TypeId = eventType,
                Date = date.ToString("yyyy-MM-dd")
            };

            Debug.WriteLine(@event.Date);

            return View(@event);
        }

        /// <summary>
        /// Adds an event to the db context
        /// </summary>
        /// <param name="event">the event to added</param>
        /// <returns></returns>
        // POST: Events/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEvent([Bind("Id,Title,Date,Duration,TypeId,Venue")] VenueEvent @event)
        {

            if (ModelState.IsValid)
            {
                var newEvent = new Event
                {
                    Id = @event.Id,
                    Title = @event.Title,
                    Date = DateTime.Parse(@event.Date),
                    Duration = @event.Duration,
                    TypeId = @event.TypeId,
                    Venue = @event.Venue
                };
                newEvent.IsActive = true;
                _context.Add(newEvent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), "Events");
            }
            return View(@event);
        }

        /// <summary>
        /// Connects an HttpClient to a selected port
        /// </summary>
        /// <param name="port">The port number to connect to</param>
        /// <returns>An HttpClient connected to the port</returns>
        private HttpClient getClient(string port)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new System.Uri("http://localhost:" + port);
            client.DefaultRequestHeaders.Accept.ParseAdd("application/json");

            return client;
        }


        private bool VenuesViewModelExists(string id)
        {
            return _context.VenuesViewModel.Any(e => e.Code == id);
        }
    }
}

ThAmCo.Events/Views/Venues/CreateEvent.cshtml
@model ThAmCo.Events.Models.VenueEvent

@{
    ViewData["Title"] = "CreateEvent";
}

<h2>Create Event</h2>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateEvent">
           
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" readonly="readonly"/>
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label"></label>
                <input asp-for="TypeId" class="form-control" readonly="readonly"/>
                <span asp-validation-for="TypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="control-label"></label>
                <input asp-for="Venue" class="form-control" readonly="readonly" />
                <span asp-validation-for="Venue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ThAmCo.Events/Views/Venues/Index.cshtml
@model IEnumerable<ThAmCo.Events.Models.AvailableVenuesDto>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "Venues", FormMethod.Get))
{
    <p>Event Type:@Html.DropDownList("eventType", (SelectList)ViewData["EventTypes"])
    Date From: @Html.Editor("beginDate")
    Date To: @Html.Editor("endDate") </p>

    <input type="submit" name="bnSubmit" />
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CostPerHour)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Capacity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CostPerHour)
                </td>
                <td>
                    <a asp-action="CreateEvent" asp-route-venueCode="@item.Code" asp-route-eventType="@ViewData["EventType"]" asp-route-date="@item.Date.ToString("yyyy/MM/dd")">Create Event</a>
                </td>
            </tr>
        }
    </tbody>
</table>